{ pkgs, ... }: {
  environment.systemPackages = with pkgs; [
    vim
    vscode
    gh
    stats
    aldente
    anki-bin
    ffmpeg_6
    yt-dlp
    arc-browser
    jdk
    firefox-unwrapped
    iina
    obsidian
    utm
    python313
    python314
    nodejs_22
    uv
    python313Packages.pip
    python311Full
    darwin.PowerManagement
    jetbrains.idea-ultimate
    maccy
    monitorcontrol
    tree
    _7zz
    code-cursor
    cargo
    rustc
    telegram-desktop
  ];
}